modLoader="javafml"
loaderVersion="[45,)"
license="Academic Free License v3.0"

[[mods]]
modId="trident_crafting_and_structures"
version="1.0"
displayName="Trident Crafting And Structures"
credits=".curseforge.com/minecraft/mc-mods/trident-crafting-and-structures-forge"
displayURL="https://mcreator.net"
authors="hir0shiyt"

[[dependencies.trident_crafting_and_structures]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4]"
    ordering="NONE"
    side="BOTH"




