modLoader="javafml"
loaderVersion="[36,)"
license="All Rights Reserved"

[[mods]]
modId="trident_crafting_and_structures"
version="2.6"
displayName="Trident Crafting & Structures "
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://curseforge.com/minecraft/mc-mods/trident-crafting-structures"
authors="Hir0shi_YT, MCreator"
description='''
don't forget to visit my other mods in : https://www.curseforge.com/members/hir0shiyt/projects
'''

[[dependencies.trident_crafting_and_structures]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




